apiVersion: v1
kind: Service
metadata:
  name: plateformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platefromservice
  ports:
    - name: platefromservice
      protocol: TCP
      port: 80
      targetPort: 80